### ISSUE TITLE
Automatically using tsconfig-paths together with ts-node when invoking gulp

### ISSUE THREAD

**Issue by NearAutomata** [dividab/tsconfig-paths#38]
I started migrating my gulpfiles to TypeScript and stumbled upon your plugin which I'd really like to use since I have some rewritten paths. Currently my `tsconfig.json` for my gulpfiles is the following:

```json
{
    "compilerOptions": {
        "lib": [
            "es7",
            "dom"
        ],
        "target": "es6",
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": true,
        "baseUrl": ".",
        "paths": {
            "@Build/*": ["Build/Library/*"],
            "*": ["node_modules/*"]
        }
    }
}
```

I started by globally installing `ts-node`, `typescript`, `gulp-cli` and `tsconfig-paths` and by running `ts-node -r tsconfig-paths/register /usr/local/lib/node_modules/gulp-cli/bin/gulp.js --tasks` manually in my repository. Unfortunately I got some weird errors that I cannot locate since it's some internal issue not in my code (even happening with an empty gulpfile):

```
/Users/Near/GitHub/oss-game-engine/node_modules/chalk/index.js:72
ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
                                                                          ^
TypeError: Cannot read property 'close' of undefined
    at Object.<anonymous> (/Users/Near/GitHub/oss-game-engine/node_modules/chalk/index.js:72:75)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Near/GitHub/oss-game-engine/node_modules/gulp-util/index.js:4:11)
    at Module._compile (module.js:649:30)
```

I'd like to know two things:

- Do you, by any chance, know what causes that error?
- Not regarding that error, what would be the best approach to combine your plugin with my gulp? (I have gulp installed globally, everything else only in my repository.)

**Comment by NearAutomata** [comment]
I figured out the answers to my questions. Basically I do not have to run `ts-node` manually and the command line that works in my case is the following: `node -r ts-node/register -r tsconfig-paths/register node_modules/.bin/gulp`. It requires `ts-node`, `tsconfig-paths`, `typescript` and `gulp-cli` as well as `gulp` installed as a local dependency.

Most likely I will add an entry to the `scripts` element of the `package.json` to call the gulp process. I still need to figure out how to include `tsconfig-paths` in my gulpfile since a direct execution of `gulp` will fail of course.

**Comment by NearAutomata** [comment]
@jonaskello Actually I was able to make it work by including the following code in the header of my `gulpfile.ts`:

```ts
import * as tsconfigPaths from "tsconfig-paths";

// tslint:disable-next-line:no-var-requires
const tsconfigJson = require("./Build/tsconfig.json");
tsconfigPaths.register({ baseUrl: ".", paths: tsconfigJson.compilerOptions.paths });
```

That allowed me to run `gulp` as usual and all paths would be resolved properly.

Slightly offtopic (maybe I should create a new issue as a feature request):
- My `./tsconfig.json` currently just extends the `./tsconfig.json` as shown below, but there is currently no way to resolve the `extends` clauses so that I can require the root `tsconfig.json`:
```json
{
    "extends": "./Build/tsconfig.json"
}
```
- The `register` method requires an argument - it would be nice to have an argument-less overload that automatically loads and parses the `tsconfig.json` in the root folder.
