### ISSUE TITLE
tsconfig-paths doesn't work with node (works with ts-node)

### ISSUE THREAD

**Issue by darkbasic** [dividab/tsconfig-paths#61]
```
$ node -r tsconfig-paths/register dist/index.js
module.js:550
    throw err;
    ^

Error: Cannot find module '@modules/webhooks'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._resolveFilename (/home/niko/WebstormProjects/guild-review/node_modules/tsconfig-paths/lib/register.js:73:40)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/niko/WebstormProjects/guild-review/server/dist/index.js:5:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```

Repro: https://github.com/darkbasic/guild-review
`yarn && yarn workspace server build && cd server && node -r tsconfig-paths/register dist/index.js`

**Comment by kel-sakal-biyik** [comment]
I have the same problem. I also tried to put tsconfig.json file under dist but didn't help.

**Comment by kel-sakal-biyik** [comment]
@darkbasic I moved a tsconfig.json file under dist folder with only path configuration and run the index.js under dist folder. By doing so it read the tsconfig file under the dist folder and it worked. You can give it a try, it might help you too.

**Comment by chanlito** [comment]
Yep just tried it not working with node, and @dotansimha solution I believe it's not optimal for production environment.

**Comment by jelling** [comment]
@bushybuffalo reported a fix [here](https://github.com/nestjs/nest/issues/986). I couldn't get it to work with my project but our configuration is more complicated than the example. I went with @kel-sakal-biyik's solution for now.

**Comment by chanlito** [comment]
So I end up using the following:

`"start": "node -r ts-node/register/transpile-only -r tsconfig-paths/register dist/main.js"`

Hope it doesn't have any negative impact.

**Comment by joseluisq** [comment]
> So I end up using the following:
> 
> `"start": "node -r ts-node/register/transpile-only -r tsconfig-paths/register dist/main.js"`
> 
> Hope it doesn't have any negative impact.

Right, but the particularity about this workaround is that I need to move `ts-node` and `tsconfig-paths` to `dependencies` section. For example to deploy my app into a Docker container.

Ideal solution (again) would be just run the transpiled code:

```js
{
  "prod": "node -r tsconfig-paths/register dist/main.js"
}
```

**Comment by patryk-wlaz** [comment]
Do you know how can I run this workaround script in pm2?

**Comment by sandangel** [comment]
May I ask for an update on this issue?

**Comment by mehtamanan** [comment]
+1

**Comment by joseluisq** [comment]
I have created a [persistent Typescript paths replacer](https://github.com/joseluisq/go-tspath/) for those wants to replace those paths directly. No runtime replace.

**Comment by jeffminsungkim** [comment]
@chanlito Tried your solution, but I'm having the following error message.

`EntityMetadataNotFound: No metadata for "SomeEntityClass" was found.`

Any ideas?

**Comment by chanlito** [comment]
@jeffminsungkim are you using `reflect-metadata`? did you import or require it?

**Comment by keesvanlierop** [comment]
> With node
> node -r tsconfig-paths/register main.js

So this bit from the README should be removed to avoid confusion

**Comment by jeffminsungkim** [comment]
@chanlito I believe that the Nest.js framework uses `reflect-metadata`.

**Comment by mkalam-alami** [comment]
I managed to make it work by using the `TS_NODE_PROJECT` env variable to point to a tweaked tsconfig file. In practice, this means:

**Launch script**

```
TS_NODE_PROJECT=tsconfig.prod.json node -r tsconfig-paths/register dist/index.js
```

**tsconfig.prod.json**

```json
{
  "extends": "./tsconfig.js",
  "compilerOptions": {
    "baseUrl": "dist"
  }
}
```

For some reason I could not override the `compilerOptions.paths` to rewrite them from the new `baseUrl`, but this particular setup seems OK.

**Comment by ejhayes** [comment]
Running into this issue as well. Seems like the common solution requires changing the `baseUrl` value so it'll work in prod. See #114

**Comment by SkaceKamen** [comment]
So the issue is, that the `baseUrl` will be resolved relative to `tsconfig.json` in root of your project, but in reality, it should point to your `dist` folder (or wherever your compiled files are).

So the node.js is trying to load your actual typescript source files. Using the `-r ts-node/register/transpile-only` workaround basically means **you will compile your typescript files twice**  because you'll be importing the typescript files (that use the paths) not the compiled javascript.

It's almost the same as running ts-node on your uncompiled index file.

One possible solution is to copy `tsconfig.json` to your `dist` path and set the current working directory (CWD) to said dist path when running the file. You have to set the CWD to `dist` because the `tsconfig.json` in CWD has the highest priority.

## Example
Project structure
```
tsconfig.json          - original tsconfig
src/index.ts           - your sources
dist/index.js          - tsc output
dist/tsconfig.json     - tsconfig copy next to the index.js
```
then you can use vscode to debug run with following config:
```
{
	"type": "node",
	"request": "launch",
	"name": "Launch Program",
	"skipFiles": [
		"<node_internals>/**"
	],
	"cwd": "${workspaceFolder}/dist/",
	"runtimeArgs": ["-r", "tsconfig-paths/register"],
	"program": "${workspaceFolder}\\dist\\src\\index.js",
	"outFiles": [
		"${workspaceFolder}/dist/**/*.js"
	]
}
```

**Comment by baba43** [comment]
@ejhayes sorry, but can you explain what you mean by that?

I'm usually specifying '.' as the baseUrl and then I get the explained error. Right now, I'm sticking with the workaround from above (https://github.com/dividab/tsconfig-paths/issues/61#issuecomment-443481737)

**Comment by DmytroSokhach** [comment]
For me all of the above didn't work.
The solution from this post worked: https://github.com/nestjs/nest/issues/986#issuecomment-509295864 

my "./tsconfig"
```json
"outDir": "./dist",
```

"./tsconfig-paths-bootstrap.js" (also in the root of the project)
```javascript
const json5 = require("json5");
const fs = require("fs");
const tsConfigPaths = require("tsconfig-paths");

const tsConfigPath = "./tsconfig.json";
const data = fs.readFileSync(tsConfigPath);
const tsConfig = json5.parse(data);

const paths = tsConfig.compilerOptions.paths;
tsConfigPaths.register({
  baseUrl: tsConfig.compilerOptions.outDir,
  paths: Object.keys(paths).reduce(
    (agg, key) => ({
      ...agg,
      [key]: paths[key].map(p =>
        p.replace(tsConfig.compilerOptions.baseUrl, tsConfig.compilerOptions.outDir),
      ),
    }),
    {},
  ),
});

**Comment by DmytroSokhach** [comment]
Solution above didn't work after deployment (probably more variables involved in building Docker image and environment variables etc.)
So tried with similar to https://github.com/dividab/tsconfig-paths/issues/61#issuecomment-513642851 to actually have proper imports in the resulting *.js in "/dist" folder.
But eventually ended with "module-alias" https://www.npmjs.com/package/module-alias as it is easy to use and just works.

**Comment by TSiege** [comment]
I ended up going with a modified solution based on @mkalam-alami's approach. The issue is that the `tsconfig.json` at the top level sets a `baseUrl` that makes sense for the top level but not the compiled js in your `dist/` or `build/`. My work around was just to copy the top level `tsconfig.json` into the `tsc` output dir and use that for the `TS_NODE_PROJECT` variable. I figured this way you don't need to add a custom tsconfig extending the projects default. Example package.json below contrasting dev vs prod runs
```
  "scripts": {
    "build": "tsc && cp ./tsconfig.json ./build/",
    "start": "ts-node-dev -r tsconfig-paths/register src/index.ts",
    "start:prod": "npm run build && TS_NODE_PROJECT=build/tsconfig.json node -r tsconfig-paths/register ./build/src/index.js",
  }
```

**Comment by g-kawin** [comment]
Thanks, @TSiege. Your solution is awesome.
FYI. Considering the tsconfig.json at the `paths` section. If you define those absolute paths be like this
```json
"paths": {
  "@/*": ["./src/*"]
}
```
you should set the `outDir` to be like "./dist/src" also.

**Comment by vilmes21** [comment]
Instead of 
```
node ./dist/entry.js
```
use:
```
NODE_PATH=./dist node ./dist/entry.js
```

inspiration from: https://youtu.be/QVxxgEyZt9Y (TDD With TypeScript, Express, NodeJS, and Mocha Unit Tests)

**Comment by ajparrah** [comment]
> TS_NODE_PROJECT=build/tsconfig.json

@TSiege Your solution is the more elegant solution while PR #114 is approved.
It's works for me. This is my full config...

## tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "outDir": "./dist",
    "rootDir": "./",
    "moduleResolution": "node",
    "baseUrl": ".",
    "paths": {
      "@server/*": ["./src/server/*"],
      "@globals/*": ["./src/globals/*"],
      "@plugins/*": ["./src/plugins/*"],
      "@modules/*": ["./src/modules/*"]
    },
    "esModuleInterop": true,
    "resolveJsonModule": true,
  },
  "exclude": ["node_modules", "dist", "tests"],
  "ts-node": {
    "require": ["tsconfig-paths/register"]
  }
}
```

## Scripts on package.json.  It's going to build then run build

### Windows user, remember using copy instead of cp command with `\\` and not `/`

```json
{
...,
"scripts": {
    "dev": "cross-env NODE_ENV=dev nodemon --exec ts-node ./src/server/app.ts",
    "build": "tsc && cp ./tsconfig.json ./dist/",
    "build:windows": "tsc && copy .\\tsconfig.json .\\dist\\",
    "start": "npm run build && cross-env TS_NODE_PROJECT=dist/tsconfig.json NODE_ENV=production node -r tsconfig-paths/register ./dist/src/server/app.js",
    "start:windows": "npm run build:windows && cross-env TS_NODE_PROJECT=dist/tsconfig.json NODE_ENV=production node -r tsconfig-paths/register ./dist/src/server/app.js"
  }
}
```

**Comment by bwyx** [comment]
instead of create new __`tsconfig.prod.json`__:
> ```
> TS_NODE_PROJECT=tsconfig.prod.json node -r tsconfig-paths/register dist/index.js
> ```

just use __`NODE_PATH`__
```sh
NODE_PATH=dist/ node dist/app.js
```

**Comment by bwyx** [comment]
instead of creating new __`tsconfig.prod.json`__:
> ```
> TS_NODE_PROJECT=tsconfig.prod.json node -r tsconfig-paths/register dist/index.js
> ```

just use __`NODE_PATH`__
```sh
NODE_PATH=dist/ node dist/app.js
```

**Comment by Ge-yuan-jun** [comment]
All above may be not elegant or convenient, I won't use these solutions because ROI is too low

**Comment by pieeee** [comment]
> As a workaround, you can do `node -r ts-node/register -r tsconfig-paths/register dist/index.js`. @kel-sakal-biyik @darkbasic

This solved my problem

**Comment by zingerj** [comment]
You can now specify `TS_NODE_BASEURL` thanks to https://github.com/dividab/tsconfig-paths/pull/185 as follows:
```
TS_NODE_BASEURL=./dist node -r tsconfig-paths/register main.js
```

**Comment by hungdao-testing** [comment]
Hi all,
In my case, if I deleted the `src` folder, the issue related to alias path happens. Here is my folder structure
![image](https://user-images.githubusercontent.com/51052135/175014913-8b97f5eb-3f82-4e68-90c5-3c131f183aa7.png)

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["ES2015", "DOM"],
    "paths": {
      "@models/*": ["src/models/*"],
      "@controllers/*": ["src/controllers/*"],
      "@routes/*": ["src/routes/*"],
      "@views/*": ["src/views/*"],
      "@utils/*": ["src/utils/*"],
      "@app_type": ["typing/app.type.ts"],
      "@config/*": ["config/*"],
      "@fixture": ["fixtureData/fixture.ts"],
      "@tests/*": ["tests/*"]
    },
    "module": "commonjs",
    "baseUrl": ".",
    "esModuleInterop": true,
    "noEmitOnError": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "typeRoots": ["typing", "./node_modules/@types"],
    "rootDirs": ["./src", "./config"],
    "outDir": "./dist",
    "sourceMap": true
  },
  "exclude": ["node_modules", "build_script.ts"]
}

```

scripts in package.json
```
     "clean": "npx rimraf ./dist/",
    "prebuild": "npm run clean",
    "build": "npx tsc -p . && npm run build:js",
    "postbuild": "npx ts-node ./build_script.ts",
    "format": "prettier --write ./src/**/*.ts ./tests/**/*.ts",
    "start": "npx cross-env NODE_ENV=production node -r ts-node/register/transpile-only -r tsconfig-paths/register ./dist/src/server.js",
```

build_script.ts
```ts
import { cp, rm } from 'shelljs'


const folderMapping: { source: string, dest: string }[] = [
  {
    source: './src/public/css',
    dest: './dist/src/public/css',
  },
  {
    source: './src/public/img',
    dest: './dist/src/public',
  },
  {
    source: './src/public/overview.html',
    dest: './dist/src/public',
  },
  {
    source: './src/public/tour.html',
    dest: './dist/src/public',
  },
  {
    source: './src/views',
    dest: './dist/src',
  }
]

function deleteFolder() {
  ['./tests', './playwright.config.ts', './dist/playwright.*', './dist/tests'].forEach(el => rm('-rf', el))
}

function main() {
  folderMapping.forEach(folderMap => {
    cp('-R', folderMap.source, folderMap.dest)
  })

  deleteFolder()
}

main()
```

I would like to know is there a way (even work-around) to fix this issue.

**Comment by rogeraraujo90** [comment]
After some confusion with a lot of approaches to fix. I was able to fix the issue just using the env var suggested in the documentation. I hope that will help others with the same problem. I believe this is not an issue anymore.

My tsconfig.json:
```json
{
  "compilerOptions": {
    "outDir": "./built",
    "allowJs": true,
    "target": "es6",
    "moduleResolution": "Node",
    "module": "CommonJS",
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "baseUrl": "./src",
    "paths": {
      "@config/*": ["./config/*"],
      "@controllers/*": ["./controllers/*"],
      "@models/*": ["./models/*"],
      "@repositories/*": ["./repositories/*"],
      "@services/*": ["./services/*"],
      "@tests/*": ["../tests/*"]
    }
  },
  "include": ["./src/**/*"]
}
```

My script to start the server:

```json
"start": "tsc && TS_NODE_BASEURL=./built node -r tsconfig-paths/register ./built/app.js",
```

Current versions are:

- Node: 16
- tsconfig-paths: "^4.1.0",
- typescript: "^4.7.4"

In case someone wanna confirm, that's the source code: https://github.com/rogeraraujo90/hey-freela

**Comment by abdulrahimiliasu** [comment]
So no solution for this yet basically, only workarounds for now ?

- I wouldn't want to `compile` again when running ` start` after already doing it when building

**Comment by PascalUlor** [comment]
@rogeraraujo90 your solution works only at runtime but the transpiled javascript does not have the resolved paths

**Comment by rogeraraujo90** [comment]
> @rogeraraujo90 your solution works only at runtime but the transpiled javascript does not have the resolved paths

I'm not working on that project currently. By I'm using a different library in a new project and it's working. Take a look at https://github.com/benyap/resolve-tspaths

**Comment by shippu-gloitel** [comment]
tsconfig.json

    "baseUrl": "./",
    "paths": {
      "@/*": ["./src/*", "./build/*"] or "@/*": ["./src/*", "./dist/*"]
    }
    
    you have to change your tsconfig like above.

**Comment by JanYork** [comment]
Is there a better way? Consider replacing paths at compile time? For example, using babel? I haven't tried it, can anyone give me a better solution? There are just too many relative path levels and I can't stand it
