### ISSUE TITLE
Bug manual registering path via object

### ISSUE THREAD

**Issue by D1no** [dividab/tsconfig-paths#9]
When I set the exact same paths like in my tsconfig.json, modules can not be resolved.

![tspath-error](https://user-images.githubusercontent.com/2397125/27014089-f5e1f61c-4ef1-11e7-922e-fa87fc90b20a.gif)

I have the following in a tsconfig.json
```json
        "baseUrl": "./",
        "paths": {
            "link-system/*": [
                "link-system/*"
            ],
            "link-interface/*": [
                "link-system/interface/*"
            ]
        }
```
all works fine after registering with
```js
const tsConfig = require("./tsconfig.json");
const tsConfigPaths = require("tsconfig-paths");

tsConfigPaths.register({
  baseUrl: tsConfig.compilerOptions.baseUrl,
  paths: tsConfig.compilerOptions.paths
});
```
BUT if I set it in js (EXACT SAME SETTING) as a test
```js
tsConfigPaths.register({
  baseUrl: tsConfig.compilerOptions.baseUrl,
  paths: {
    "link-system/*": [
      "_system/*"
    ],
    "link.interface/*": [
      "_system/interface/*"
    ]
  }
});
```
it leads to:
```bash
Error: Cannot find module 'link-interface/***ANNOTATED***'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module._load (/Users/worker/development/***ANNOTATED***/_worker/node_modules/tsconfig-paths/lib/register.js:26:31)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/worker/development/***ANNOTATED***/_worker/main.ts:8:1)
    at Module._compile (module.js:569:30)
    at Module.m._compile (/Users/worker/development/***ANNOTATED***/_worker/node_modules/ts-node/src/index.ts:382:23)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/worker/development/***ANNOTATED***/_worker/node_modules/ts-node/src/index.ts:385:12)
```

I was thinking a was doing something wrong. But console logging the tsconfig and manual tsconfig are exactly the same object.

**Comment by jonaskello** [comment]
What does your `npm start` script look like?

**Comment by jonaskello** [comment]
@D1no I tried a quick repro of your issue here:

https://github.com/jonaskello/tsconfig-paths-repro-9

You can run `yarn start` and `yarn start2`. Both works for me, could you check if you are doing something different?

**Comment by D1no** [comment]
As its quite a while ago, I'd need to check. I think we worked around the issue and if your repros work, I guess the mistake had to be on our side. :/

I get back to this when we need to touch that part of the codebase again.

**Comment by jonaskello** [comment]
@D1no Didn't see your update until now. Is that code you posted still causing problems?

**Comment by Jontem** [comment]
Closing. Please feel free to open the issue if it still exists
